### NUMPY

In [4]:
import numpy as np 

# converting an list to array
ec = [1200 , 3400 , 2900 , 1800, 2500]
energy_consumption = np.array(ec)

print("Energy consumption (in MWh) for different Renewable sources:")
print(energy_consumption)

Energy consumption (in MWh) for different Renewable sources:
['1200' '3400' 'rohit' '1800' '2500']


#### 1. CREATING MATRIX

In [8]:
# 1d array
A = np.ones(4)
A2 = np.ones((2,2))

# 2d array
print(A)
print(A2)

# array with zeros
M = np.zeros(4)
print(M)

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[0. 0. 0. 0.]


#### 2. IDENTITY MATRIX

In [9]:
i = np.identity(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 3. Sum of array elements

In [16]:
ec = [1200 , 3400 , 2900 , 1800, 2500]
energy_consumption = np.array(ec)

total = np.sum(energy_consumption)
print("The total oonsumption is :" ,total)

The total oonsumption is : 11800


#### 4. MEAN

In [17]:
mean = np.mean(energy_consumption)
print("The mean is :", mean)

The mean is : 2360.0


#### 5. STANDARD DEVIATION

In [20]:
standard_deviation = np.std(energy_consumption)
print(standard_deviation
     )

781.2809993849844


#### 6. RESHAPING

In [35]:
energy_consumption2 = np.array([1200 , 3400 , 2900, 1800, 2500 , 1800])

# for reshaping the size of array should be same which is = 6
reshaped = energy_consumption2.reshape((3,2))
reshaped2 = energy_consumption2.reshape((6,1))
reshaped3 =  energy_consumption2.reshape((2,3))

print("The new reshaped" , reshaped)
print("The new reshaped" , reshaped2)
print("The new reshaped" , reshaped3)

# flatteining the array --> means converting nD array into 1D 
print("The flatten array is:",reshaped.flatten())



The new reshaped [[1200 3400]
 [2900 1800]
 [2500 1800]]
The new reshaped [[1200]
 [3400]
 [2900]
 [1800]
 [2500]
 [1800]]
The new reshaped [[1200 3400 2900]
 [1800 2500 1800]]
The flatten array is: [1200 3400 2900 1800 2500 1800]


#### 7. TRANSPOSE

In [34]:
# Tranpose 
print("Tranpose of array is: ", reshaped3.T)

Tranpose of array is:  [[1200 1800]
 [3400 2500]
 [2900 1800]]


#### 8. RESIZING

In [38]:
# resizing the array

energy_consumption2 = np.array([1200 , 3400 , 2900, 1800, 2500 , 1800])
resized = np.resize(energy_consumption2 , (1,9))
print(resized)

[[1200 3400 2900 1800 2500 1800 1200 3400 2900]]


#### 9. OTHER NUMPY METHODS

In [61]:
# genrating random integer
print(np.random.randint(0 , 10, 1))

# multiplication of two array
print("The self multiplication of energy consumption array is :",np.dot(energy_consumption2 , energy_consumption2))

# power ele by 2
l = [2, 4, 5, 6]
arr = np.array(l)
print("The square of each element from the array: " , arr, "is" , np.power(arr, 2))

# square root of an elements of array
print("The square root of each element from the array: " , arr, "is" ,np.sqrt(arr))

# max element from array
print("The max element from the array: " , arr, "is" , np.max(arr))
      
# Creates an array with evenly spaced values from 0 to 9
print(np.arange(10))

[5]
The self multiplication of energy consumption array is : 34140000
The square of each element from the array:  [2 4 5 6] is [ 4 16 25 36]
The square root of each element from the array:  [2 4 5 6] is [1.41421356 2.         2.23606798 2.44948974]
The max element from the array:  [2 4 5 6] is 6
[0 1 2 3 4 5 6 7 8 9]
